backend:
  name: git-gateway
  repo: charitygamble/spookybookshelf
  branch: main # Branch to update
publish_mode: editorial_workflow
folder: "src/reviews"
extension: "html"
format: "frontmatter"
media_folder: "public/assets/covers"
public_folder: "/assets/covers"
collections:
 - name: "reviews"        #The name of the collection and should match our posts.json file's tag
   label: "Reviews"       #The name of the collection on the CMS itself
   folder: "reviews"      #The folder that our blog posts will be loaded from and saved to
   create: true             #Tells the CMS that new posts can be created
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  #this sets the URL for the post
   fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: ""}
      - {label: "Post Body", name: "body", widget: "markdown"}
